### ISSUE TITLE
Question: is the project still active?

### ISSUE THREAD

**Issue by wayneyaoo** [adambajguz/Typin#210]
Sorry I had to use Issue to ask questions since I couldn't find the Discussion button in the repo.

Coming from a Clifx user, I really like the extensibility and some of the proper interface definition e.g., IServiceProviderFactory, IHelpWriter, ICommandExecutor, not to mention middleware. They're awesome. Thanks very much for your time on making Clifx better!

While I can see there were intensive activities in Aug-Nov last year, there has not been many update since then, can I still rely on this project? Asking because I'm at a early stage of adopting this project in my work, and wondering if this is sustainable.

Thank you!

**Comment by adambajguz** [comment]
Hi,
yes, the project **is active**! Every bug reported to Typin 3.0.4 will be still fixed :)

The lack of changes on the master branch is due to the ongoing generic host refactor on the branch [feature/issue-3_cli-host-refactor](https://github.com/adambajguz/Typin/tree/feature/issue-3_cli-host-refactor), which will also introduce a better-organized source code and even more extensibility (dynamic commands, better middlewares through [PackSite.Library.Pipelining](https://github.com/PackSite/Library.Pipelining), and better CLI modes).
